# Generated by Django 4.2.16 on 2024-10-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_whyus_description_en_whyus_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=212)),
                ('savol_uz', models.CharField(max_length=212, null=True)),
                ('savol_en', models.CharField(max_length=212, null=True)),
                ('savol_ru', models.CharField(max_length=212, null=True)),
                ('javob', models.CharField(max_length=212)),
                ('javob_uz', models.CharField(max_length=212, null=True)),
                ('javob_en', models.CharField(max_length=212, null=True)),
                ('javob_ru', models.CharField(max_length=212, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fullname_uz', models.CharField(max_length=100, null=True)),
                ('fullname_en', models.CharField(max_length=100, null=True)),
                ('fullname_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NimaUchunBiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_name_uz', models.CharField(max_length=100, null=True)),
                ('company_name_en', models.CharField(max_length=100, null=True)),
                ('company_name_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OurSertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('cat', models.CharField(max_length=100)),
                ('cat_uz', models.CharField(max_length=100, null=True)),
                ('cat_en', models.CharField(max_length=100, null=True)),
                ('cat_ru', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('plan_uz', models.CharField(max_length=100, null=True)),
                ('plan_en', models.CharField(max_length=100, null=True)),
                ('plan_ru', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('get', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fullname_uz', models.CharField(max_length=100, null=True)),
                ('fullname_en', models.CharField(max_length=100, null=True)),
                ('fullname_ru', models.CharField(max_length=100, null=True)),
                ('job', models.CharField(max_length=100)),
                ('job_uz', models.CharField(max_length=100, null=True)),
                ('job_en', models.CharField(max_length=100, null=True)),
                ('job_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fullname_uz', models.CharField(max_length=100, null=True)),
                ('fullname_en', models.CharField(max_length=100, null=True)),
                ('fullname_ru', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='kimlar_uchun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nimauchunbiz'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio'),
        ),
        migrations.AddField(
            model_name='category',
            name='xodim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.xodim'),
        ),
    ]
