# Generated by Django 4.2.16 on 2024-10-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_category_faq_feedback_nimauchunbiz_ourclients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='xodim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.xodim'),
        ),
    ]
